dialogues = [
    "You know the eighth level of hell is reserved for snake oil peddlers, right?",
    "Take your hands of me or so help me I will break your arm.",
    "Oh, like you’ve never done something stupid when drunk.",
    "If you get the others on board I’ll give you my vote too.",
    "Listen to a bunch of True Believers argue about the nature of divine truth? I’ll take a hard pass, thanks.",
    "You need it by tomorrow?? … it’s a big ask, but I think I can do it.",
    "It won’t be long before you betray your friends just for a drink.",
    "The others might not know the truth about you, but I do.",
    "Look, none of what happened last night is your fault.",
    "It’s okay. This is how it’s supposed to happen.",
    "So what’s so important about this waterfall?",
    "So when are you going to ask them out?",
    "Can someone please tell me what the hell that thing on the kitchen floor is?",
    "Please don’t make me go in there alone.",
    "How long until we reach the port?",
    "You’re gonna stay in that forest overnight? You know it’s haunted, right?",
    "So… anyone know how to skin a dear?",
    "Hey, I neeeed your helllp. Think ssssomeeeone ssspiked my drink. I’m at th-",
    "He’s has nightmares every night for the past week. He’s tired.",
    "Listen. This is important. Stay away from the temple tomorrow.",
    "Still no sign of them. What if they don’t come home?",
    "okay, so what’s the escape plan now?",
    "The truth is I just don’t trust you anymore.",
    "Why are you here? I didn’t ask for your help.",
    "Please don’t make me go in there alone.",
    "They’d better get back soon, we need five people for the ritual.",
    "Be honest with me. Did you write the letter?",
    "I’m sorry for what I said about your dad, okay?",
    "Hurry! They’re pulling up in the driveway!",
    "You guys can all hear that as well, right??",
    "What I don’t get is why they were in the village in the first place.",
    "It’ll take about 24 hours to clear out of her system. We should lay low until then.",
    "Be careful, she’s got that twitchy eyelid thing that happens when she’s pissed off.",
    "… am I the only one who remembers this?",
    "We all know you’re too much of a narcissistic asshole to ever accept this is your fault.",
    "You handled yourself well today. I’m glad we’re on the same side.",
    "Of course I don’t trust them. And I don’t understand why you do. Whatever it is you see in them, I’m missing it.",
    "Do you really think she would have sent you, if she didn’t think you were up to the task?",
    "No. You don’t understand. The police want to investigate.",
    "Please stop asking if I’m in pain. I’m trying to distract myself and you’re not helping.",
    "If it’s all the same to you, I’d prefer not to get choke-slammed into a wall again.",
    "He’s not coming home.",
    "I’m not going to stand here and watch you crash and burn.",
    "I was the oldest, and they just assumed I could take care of myself.",
    "I don’t know why you’re surprised. She was just doing what she always does. She was keeping us safe.",
    "Just let me go and I won’t tell anyone you did this.",
    "I literally just finished unpacking. I’m not moving home again without a damn good reason why’.",
    "Its me. I’m the problem, aren’t I?",
    "We have a problem. I’ve sort of been accused of murder.",
    "I can’t believe we’re even having this conversation. I don’t have a drug problem!",
    "Yes, I agreed to be interviewed. Is this going to be a problem?",
    "You’re the one who made the deal! If you can’t afford to pay them then that’s your problem.",
    "Do you want to go grab a drink? There’s a bar right across the street and I need a break.",
    "We have to act fast. At best, we’ve probably got two days, after that… they’ll break quickly.",
    "Hey. You should get here ASAP. She’s managed to break the code.",
    "We need to get you as far away from this place as possible.",
    "What are you talking about? I’ve never even been to this country before, let alone this place.",
    "See that tower over there? Pretty sure that means we are not just in the wrong place, but about 70 Kilometers from the right place.",
    "It’s not that I don’t like this place, it’s that this place doesn’t like me.",
    "It’s just this time of the year, y’know. It… takes their head to a dark place.",
    "The others might not know how you got that shiner, but I do. I saw it… and know who the person who gave it to you is.",
    "Please. You know how I feel about birthdays.",
    "I know this is supposed to be a holiday, but… we got work to do.",
    "I don’t know what’s wrong with you, and I don’t know how to fix it.",
    "We need to generate enough power to keep the system on.",
    "Come on, you know the system by now. Hand it over.",
    "I think I crashed the system.",
    "Can you just take it easy for a week and give your immune system some time to do it’s damn job?",
    "We have to get some water into his system, otherwise he’s dead.",
    "congratulations, you’re famous. Now tell everyone you’re a fraud.",
    "They’re a famous organisation, but no one really knows what they actually do.",
    "Why are you doing this? I don’t want to be famous!",
    "This is going to make us famous.",
    "They were famous, once. Then they quit and started a bike shop.",
    "They’ve been such an asshole since they became famous.",
    "I’ve heard about your famous escapade.",
    "You’re kind of famous for it.",
    "Famous? I’ve never heard of it.",
    "So. Are you enjoying being famous?",
    "Why are you running?",
    "See that hedge running along the top of the field?  That’s where they buried him.",
    "Why do you think they’re running?",
    "Given everything that’s happened the last few days, I think I deserve to know what you’re running from.",
    "And you’re running it now?",
    "If you see a red car, start running.",
    "When are we going to stop running?",
    "How much longer will it be running for?",
    "I’m tired. My head hurts. And my goddamn nose won’t stop running.",
    "They’re going to be running forever.",
    "You swore you were done with this kind of work! You PROMISED me!",
    "I just need to borrow it for a couple of hours, I promise I’ll give it back.",
    "Yes, they show some promise, but if they don’t start thinking more about covering their tracks, they’re gonna get arrested pretty quickly.",
    "I made a promise to them and I have to keep it. So yes, I’m going to France.",
    "If we get out of this I promise you, the first place we’re going is a sushi bar.",
    "we might need to stage an intervention. They’re reading opinion pieces about themself again.",
    "Hey, hey, I need you to keep talking to me. Can you do that?",
    "You need to make this whole situation go away. Okay?",
    "Let’s just keep this on the down-low, yeah? No need to make him worry.",
    "So this is where you grew up? It’s… uh. Posher than I expected.",
    "This symbol… I’ve seen it in my research. Where did you get this?",
    "Any idea where they’re taking us?",
    "Yes, I let him borrow my keys. Where are you going with this?",
    "Excuse me, could you tell me where the special collection is, please?",
    "Five murders in seven years… You sure this place isn’t haunted?",
    "It’s raining. It’s three in the morning. I’m cold, I’m wet, and your friend hasn’t shown up.",
    "I can’t believe I’m even going to ask this, but… why are there two syringes full of blood in the freezer?",
    "I believe in the things for which I have proof. That doesn’t include an afterlife.",
    "Police say the fugitives are armed, and highly dangerous, and ask that if you see them, call the hotline number, but do not approach them.",
    "Why are you so surprised? Believe it or not I do actually tell the truth sometimes.",
    "You’ve got five minutes to make me believe you’re telling the truth.",
    "I can’t believe we’re having to rely on public transport. When this is over you’re learning to drive.",
    "You’re asking me to lie to my sister. I can’t do it.",
    "You don’t have to lie. We all know this is what I deserve.",
    "Funny story: we may have a rather large bounty on our heads. We should probably lie low for a while.",
    "It was a pretty typical cryptic response from the oracle - they said the answers lie in the frozen mouth. I have no idea what that means.",
    "If I don’t meet you there in three days, turn back.",
    "If I call you, will you come back?",
    "I think pretty much the entire world knows you’re back now.",
    "look, we have to get this back to them on time, or they will die.",
    "I just want to get into better shape so that if they come back I don’t get my ass kicked again.",
    "… that’s a worrying amount of blood.",
    "I can’t do this anymore. I can’t keep watching you throw yourself in danger and cleaning the blood out of your wounds when we get home.",
    "Just shut up and help me wash this blood out of the carpet.",
    "What, I’m just supposed to keep forgiving you because you’re blood? Nu-uh.",
    "Is that blood? Please tell me that’s not blood. Oh god. It’s blood, isn’t it?",
    "This is the cave where he was supposedly born.",
    "Yeah, this is where…",
    "Look, can we just have one conversation where you don’t lecture me, please?",
    "Why would I know where your phone is?",
    "where are we supposed to meet after the job’s done?",
    "They’re not here. the place is a mess. I don’t think anyone’s lived here for a while.",
    "Not judging you or anything, but that relationship is a mess. And you should walk away.",
    "… I’ve been thinking awhile… about that mess back on the ship.",
    "Sorry about the mess.",
    "…shouldn’t your hair be red?",
    "If you just paint it red it’ll fit right in.",
    "Hmm? It means ‘red’. Why?",
    "…I’ve been getting these weird letters in the post. Always in a red envelope.",
    "Yeah, I’m here. Glad you’re not. They’ve redecorated. In red.",
    "Oh my god, you’re actually serious. You really do want to try and bargain with that asshole.",
    "God I wish you were here. Wish you weren’t dead.",
    "What, did you think your god was going to start caring now, all of a sudden?",
    "If you say you knew what was going on as well, so help me god I will kick your ass.",
    "So. Who’s going to explain to me why we’re standing in the middle of a graveyard?",
    "Only two of the defence posts are still standing and I have no idea how long they’ll last.",
    "See the one standing over there by the fountain? Black jeans, blue coat? That’s them.",
    "If we do this job, it’ll put us in good standing with them, and then maybe they’ll grant us a bloody audience.",
    "She went off that way somewhere. Said there were some standing stones she needed to see. She seemed pretty excited about them.",
    "We have a long standing relationship with them. I would appreciate it if you didn’t jeopardise that.",
    "Doesn’t matter if you like him or not. He has a high standing in that group and we need him on our side.",
    "I need everyone to stay standing, and stay quiet.",
    "I don’t care how spectacular it is. I’m not standing here in the sodding rain just to see some bloody fireworks. You’re on your own.",
    "Lose them, but don’t get lost yourself, okay? I’m not going in there to get you out if you do.",
    "Do you even know how much it’s cost him to get here? How much he’s lost??",
    "And you think I’m going to help you out? Get lost.",
    "Sooooo…. I lost the bet. And my money. And your money. And also the car.",
    "What, did you think we chose this life because we’d lost something? That we’ve all got some tragic backstory? Did you think that you’d come along and heal us and we’d see the error of our ways?",
    "Yeah, well, the prophesies can stay lost. Much better that way.",
    "Lost? Like… existential-crisis lost? Or like… you’re-too-drunk-to-recognise-where-you-are lost?",
    "There’s no way of knowing how much we lost until we can start it up again. But just… prepare for the worst, yeah?",
    "Yes, we are indeed, absolutely lost. And that’s fine, because this plan doesn’t at all depend on us knowing where we are.",
    "What possible reason could you have to justify leaving us like this?",
    "To be honest, the times when you start listening to reason are the times I start to really worry about you.",
    "So… they’re just… hunting us? For no reason?",
    "Hey. They’re looking for a reason throw you in jail. don’t give them one.",
    "well at least one of you still has the capacity to use your sense of reason.",
    "Look, I took care of them. We’re not being followed anymore. There’s no reason to be this cautious and slow.",
    "I know we have every reason to be skeptical, here. But… I trust them.",
    "There’s got to be a reason she left this here for us. It’s a clue, or a key, or… something.",
    "Kiddo, I can think of ten reasons you shouldn’t marry them off the top of my head. By the time you get to the altar, that list’s gonna be triple digits.",
    "Oh come on, it’s not that dangerous.",
    "You’re treading dangerous territory here; they don’t like to talk about it.",
    "Why are you so obsessed with doing the most dangerous thing?!",
    "I’m not sure your have the same idea of ‘not dangerous’ as the rest of us do.",
    "I’m in a very dangerous position right now.",
    "Do you realise how dangerous that was?",
    "It might be dangerous, but at least it’s not stupid.",
    "Are they really that dangerous?",
    "Oh, like you’ve never done anything dangerous. Remember that time you deliberately drove your car into the ocean?",
    "That wasn’t particularly appropriate, y’know.",
    "I intend to… appropriate it.",
    "It’s never been more appropriate.",
    "I honestly don’t think they know what’s appropriate.",
    "We need to appropriate some funds, sharpish.",
    "They’re going to appropriate our idea!",
    "Well, at least they’re in the appropriate place.",
    "Could you please try and behave in an appropriate manner?",
    "I have no idea what the appropriate etiquette is, here!",
    "uh… I have no idea how to work this thing.",
    "of course I’m pissed! That was your idea and you just let them take it!",
    "Soooo… someone has an idea about how to get out of here, right?",
    "I take it back. That’s not a bad idea.",
    "I take it back. That’s not a stupid idea, it’s a really stupid idea.",
    "Look his plan is based on the idea that you’d be dead by now. We can use that to our advantage.",
    "There’s nothing you can do to make them trust you. They got obsessed with the idea that we’ll betray them and there’s no shaking it.",
    "I’m sorry. I had no idea it was this bad.",
    "do you have any idea how much pain I’m in???",
    "Hey! At least my idea doesn’t have a body count!",
    "Could you try to be a little less conspicuous?",
    "Oh, like that’s not conspicuous at all.",
    "There’s a conspicuous absence of a way out of here.",
    "is that blood? Ugh. Too conspicuous. Here, wear this.",
    "Don’t worry, you’ll be able to tell which car is mine. It’s pretty conspicuous.",
    "So yeah. That’s why I keep it covered. Pretty conspicuous.",
    "We’re going to a ballroom dance. You’re wearing a hoodie. Do you not understand how conspicuous that is??",
    "how many weapons do you think I can take without looking conspicuous?",
    "congratulations, for once we need to you look as conspicuous as possible - I trust you can handle that?",
    "Are you sure they were being serious?",
    "Do you understand how serious this is?",
    "Ugh. I’m going to have some serious words with them.",
    "I can never tell if they’re being serious.",
    "I’m honestly not sure they’ve ever been serious in their life.",
    "Why are you being so serious? What’s wrong?",
    "This had better be serious; I haven’t slept in three days and I need a goddamn nap.",
    "I saw them earlier. They looked pretty serious.",
    "I was seriously afraid they’d leave.",
    "I never asked you to love me, ok? In fact, I specifically told you not to!",
    "I love you…", "Let’s try that again later when you aren’t bleeding out, alright?",
    "You know, a definition of insanity is trying the same thing over and over again and expecting different results. When did you realize you were insane?",
    "The electricity is still running.",
    "We live by a strict code.", "No we don’t. We’ve been winging it since day one.",
    "This is gonna hurt, but you have to be quiet. Ok?",
    "I thought you said you weren’t dead!", "I wasn’t exactly lying…",
    "Just so you know, I’m about 30 seconds away from lighting something on fire.",
    "Believe in yourself. If you don’t you risk being forgotten and fading away.",
    "I was born to suffer. But, God, has life been worth it.",
    "Yes, all forests are haunted. Although, most are not really haunted by things that were once human.",
    "Why so silent, my friends? Did you think I had left you for good? How ridiculous. You’ll never be rid of me.",
    "You can’t rob your own grave.",
    "I can feel my heartbeat in my face."
]
