
greetings = [
    "ahoy",
    "how's it hanging?",
    "good morning",
    "what's the dizzle?",
    "good day",
    "what's up?",
    "how's it hanging?",
    "what's new?",
    "konnichi wa",
    "sup",
    "guten Tag",
    "hola",
    "howzit?",
    "how do?",
    "good afternoon",
    "what's the dilly?",
    "what's poppin'?",
    "how ya goin?",
    "salutations",
    "what's happening?",
    "hello",
    "hey",
    "yello",
    "what ho?",
    "how's it going?",
    "how goes it?",
    "wussup?",
    "aloha",
    "good evening",
    "What's in the bag?",
    "'sup, b?",
    "what's the rumpus?",
    "holla",
    "what's cracking?",
    "what up?",
    "greetings",
    "good night",
    "what's shaking?",
    "'sup?",
    "what's crackin'?",
    "wassap?",
    "whazzup?",
    "yo",
    "howsyamomanem?",
    "what's cooking?",
    "what's crack-a-lackin'?",
    "what's the haps?"
]
